//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections;

namespace Assets.Scripts.Behaviour
{
	public class PauseGame: MonoBehaviour
	{
		private GameObject PauseWindow;
		private Boolean isPaused;

		void Awake(){
			//PauseWindow = GameObject.FindGameObjectWithTag ("PauseWindow");
			PauseWindow = transform.FindChild ("PauseWindow").gameObject as GameObject;
		}
		 
		void Start(){
			PauseWindow.SetActive (false);
			isPaused = false;
		}

		void Update(){
			if(Input.GetKeyDown(KeyCode.Escape)){
				if(!PauseWindow.activeInHierarchy && isPaused == false){
					PauseWindow.SetActive(true);
					Time.timeScale = 0;
					isPaused = true;
				}
			}
		}

		public void OnCloseButtonClicked(){
			if (isPaused) {
				PauseWindow.SetActive (false);
				Time.timeScale = 1;
				isPaused = false;
			}
		}

		public void OnResumeButtonClicked(){
			OnCloseButtonClicked ();
		}

		public void OnReloadButtonClicked(){
			PauseWindow.SetActive (false);
			Time.timeScale = 1;
			Application.LoadLevel (Application.loadedLevel);
		}

		public void OnLevelSelectionButtonClicked(){
			Time.timeScale = 1;
			Application.LoadLevel("LevelSelection");
		}

		public void sampleCode(){
			if(!PauseWindow.activeInHierarchy && isPaused == false){
				PauseWindow.SetActive(true);
				Time.timeScale = 0;
				isPaused = true;
			}
		}

	}
}

